from .charts import *
from gleaner.model.gleaner_chart import ChartKeyTokens

chart_map: dict[ChartKeyTokens, type] = {
    # Bar Chart (Single)
    ("bar", "Q", None, None, None, "count", None): SingleBarChart,
    ("bar", "T", None, None, "year", "count", None): SingleBarChart,
    ("bar", "T", None, None, "month", "count", None): SingleBarChart,
    ("bar", "T", None, None, "dayofweek", "count", None): SingleBarChart,
    ("bar", "N", "Q", None, None, "mean", None): SingleBarChart,
    ("bar", "N", "Q", None, None, "sum", None): SingleBarChart,
    ("bar", "N", "Q", None, None, "max", None): SingleBarChart,
    ("bar", "N", "Q", None, None, "min", None): SingleBarChart,
    ("bar", "T", "Q", None, "year", "mean", None): SingleBarChart,
    ("bar", "T", "Q", None, "month", "mean", None): SingleBarChart,
    ("bar", "T", "Q", None, "dayofweek", "mean", None): SingleBarChart,
    # Bar Chart (Stacked)
    ("bar", "N", "Q", "N", None, "sum", None): MultipleBarChart,
    ("bar", "T", "Q", "N", "year", "sum", None): MultipleBarChart,
    ("bar", "T", "Q", "N", "month", "sum", None): MultipleBarChart,
    ("bar", "T", "Q", "N", "dayofweek", "sum", None): MultipleBarChart,
    # Bar Chart (Grouped)
    ("bar", "N", "Q", "N", None, "mean", None): MultipleBarChart,
    ("bar", "T", "Q", "N", "year", "mean", None): MultipleBarChart,
    ("bar", "T", "Q", "N", "month", "mean", None): MultipleBarChart,
    ("bar", "T", "Q", "N", "dayofweek", "mean", None): MultipleBarChart,
    ("bar", "N", "Q", "N", None, "max", None): MultipleBarChart,
    ("bar", "T", "Q", "N", "year", "max", None): MultipleBarChart,
    ("bar", "T", "Q", "N", "month", "max", None): MultipleBarChart,
    ("bar", "T", "Q", "N", "dayofweek", "max", None): MultipleBarChart,
    ("bar", "N", "Q", "N", None, "min", None): MultipleBarChart,
    ("bar", "T", "Q", "N", "year", "min", None): MultipleBarChart,
    ("bar", "T", "Q", "N", "month", "min", None): MultipleBarChart,
    ("bar", "T", "Q", "N", "dayofweek", "min", None): MultipleBarChart,
    # Single Line Chart
    ("line", "T", None, None, "year", "count", None): LineChart,
    ("line", "T", None, None, "month", "count", None): LineChart,
    ("line", "T", None, None, "dayofweek", "count", None): LineChart,
    ("line", "T", "Q", None, "year", "mean", None): LineChart,
    ("line", "T", "Q", None, "month", "mean", None): LineChart,
    ("line", "T", "Q", None, "dayofweek", "mean", None): LineChart,
    ("line", "T", "Q", None, "year", "sum", None): LineChart,
    ("line", "T", "Q", None, "month", "sum", None): LineChart,
    ("line", "T", "Q", None, "dayofweek", "sum", None): LineChart,
    ("line", "T", "Q", None, "year", "max", None): LineChart,
    ("line", "T", "Q", None, "month", "max", None): LineChart,
    ("line", "T", "Q", None, "dayofweek", "max", None): LineChart,
    ("line", "T", "Q", None, "year", "min", None): LineChart,
    ("line", "T", "Q", None, "month", "min", None): LineChart,
    ("line", "T", "Q", None, "dayofweek", "min", None): LineChart,
    # Multiple Line Chart
    ("line", "T", "Q", "N", "year", "mean", None): LineChart,
    ("line", "T", "Q", "N", "month", "mean", None): LineChart,
    ("line", "T", "Q", "N", "dayofweek", "mean", None): LineChart,
    ("line", "T", "Q", "N", "year", "sum", None): LineChart,
    ("line", "T", "Q", "N", "month", "sum", None): LineChart,
    ("line", "T", "Q", "N", "dayofweek", "sum", None): LineChart,
    ("line", "T", "Q", "N", "year", "max", None): LineChart,
    ("line", "T", "Q", "N", "month", "max", None): LineChart,
    ("line", "T", "Q", "N", "dayofweek", "max", None): LineChart,
    ("line", "T", "Q", "N", "year", "min", None): LineChart,
    ("line", "T", "Q", "N", "month", "min", None): LineChart,
    ("line", "T", "Q", "N", "dayofweek", "min", None): LineChart,
    # Stripplot
    ("tick", "Q", None, None, None, None, None): StripPlot,
    ("tick", "Q", "N", None, None, None, None): StripPlot,
    # Boxplot
    ("boxplot", "Q", None, None, None, None, None): BoxPlot,
    ("boxplot", "Q", "N", None, None, None, None): BoxPlot,
    # Pie Chart
    ("arc", "N", None, None, None, "count", None): PieChart,
    ("arc", "N", "Q", None, None, "sum", None): PieChart,
    ("arc", "N", "Q", None, None, "mean", None): PieChart,
    ("arc", "N", "Q", None, None, "max", None): PieChart,
    ("arc", "N", "Q", None, None, "min", None): PieChart,
    # Scatter Plot
    ("point", "Q", "Q", None, None, None, None): ScatterPlot,
    ("point", "Q", "Q", "N", None, None, None): ScatterPlot,
    ("point", "Q", "Q", "Q", None, None, None): ScatterPlot,
    # Heatmap
    ("rect", "Q", "Q", None, None, None, "count"): Heatmap,
    ("rect", "N", "N", None, None, None, "count"): Heatmap,
    ("rect", "Q", "Q", "Q", None, None, "mean"): Heatmap,
    ("rect", "Q", "Q", "Q", None, None, "max"): Heatmap,
    ("rect", "Q", "Q", "Q", None, None, "min"): Heatmap,
    ("rect", "Q", "Q", "Q", None, None, "sum"): Heatmap,
    ("rect", "N", "N", "Q", None, None, "mean"): Heatmap,
    ("rect", "N", "N", "Q", None, None, "max"): Heatmap,
}
